apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: twitch-tag-inventory-migration
spec:
  template:
    spec:
      template:
        spec:
          maxRetries: 1
          timeoutSeconds: 300
          containers:
            - image: IMAGE_PLACEHOLDER
              env:
                - name: DB_APP_NAME
                  value: twitch_tag_inventory
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: latest
                      name: twitch-tag-inventory-db-app-password
            - image: cloudflare/cloudflared:latest
              args:
                - access
                - tcp
                - --hostname
                - db.yuniruyuni.net
                - --url
                - localhost:5432
              env:
                - name: TUNNEL_SERVICE_TOKEN_ID
                  valueFrom:
                    secretKeyRef:
                      key: latest
                      name: cf-db-access-client-id
                - name: TUNNEL_SERVICE_TOKEN_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: latest
                      name: cf-db-access-client-secret
              resources:
                limits:
                  cpu: "0.5"
                  memory: "128Mi"
