apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stream-tag-inventory
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
          env:
            - name: DB_APP_NAME
              value: stream_tag_inventory
            - name: DB_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: stream-tag-inventory-db-app-password
        - image: cloudflare/cloudflared:latest
          args:
            - access
            - tcp
            - --hostname
            - db.yuniruyuni.net
            - --url
            - localhost:5432
          env:
            - name: TUNNEL_SERVICE_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: cf-db-access-client-id
            - name: TUNNEL_SERVICE_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: cf-db-access-client-secret
          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
