services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      migration:
        condition: service_completed_successfully
    develop:
      watch:
        - action: rebuild
          path: ./client/src
        - action: rebuild
          path: ./server/src
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./server/package.json

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    environment:
      - DB_APP_NAME=twitch_tag_inventory
      - DB_PASSWORD=twitch_tag_inventory
      - PGHOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./schema

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: twitch_tag_inventory
      POSTGRES_PASSWORD: twitch_tag_inventory
      POSTGRES_DB: twitch_tag_inventory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twitch_tag_inventory"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
