name: Visual Regression Test

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      actual-sha: ${{ steps.prepare.outputs.actual-sha }}
      actual-cache-hit: ${{ steps.prepare.outputs.actual-cache-hit }}
      expected-sha: ${{ steps.prepare.outputs.expected-sha }}
      expected-cache-hit: ${{ steps.prepare.outputs.expected-cache-hit }}
    steps:
      - uses: yorifuji/easy-vrt/prepare@v2
        id: prepare

  expected:
    if: ${{ !cancelled() && !failure() && needs.prepare.outputs.expected-cache-hit != 'true' }}
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.expected-sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium

      - name: Generate screenshots
        run: bun run vrt:screenshots

      - uses: yorifuji/easy-vrt/expected@v2
        with:
          expected-dir: e2e/__snapshots__/
          expected-cache-key: ${{ needs.prepare.outputs.expected-sha }}

  actual:
    if: ${{ !cancelled() && !failure() && needs.prepare.outputs.actual-cache-hit != 'true' }}
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.actual-sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium

      - name: Generate screenshots
        run: bun run vrt:screenshots

      - uses: yorifuji/easy-vrt/actual@v2
        with:
          actual-dir: e2e/__snapshots__/
          actual-cache-key: ${{ needs.prepare.outputs.actual-sha }}

  compare:
    if: ${{ !cancelled() && !failure() }}
    needs: [prepare, expected, actual]
    runs-on: ubuntu-latest
    steps:
      - uses: yorifuji/easy-vrt/compare@v2
        with:
          expected-cache-key: ${{ needs.prepare.outputs.expected-sha }}
          actual-cache-key: ${{ needs.prepare.outputs.actual-sha }}
          summary-comment: true
          review-comment: true
